# Generated by Django 5.2.1 on 2025-12-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
                ('rating', models.FloatField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=250, null=True)),
                ('img_url', models.URLField(max_length=250)),
            ],
        ),
    ]
